version: "3.5"
name: dev
services:
  cockroach:
    image: cockroachdb/cockroach:latest
    restart: always
    ports:
      - "26257:26257"
    environment:
      COCKROACH_USER: $DB_USER
      COCKROACH_DATABASE: $DB_NAME
    command: start-single-node --insecure      
    volumes:
      - "./db/data:/cockroach/cockroach-data"