version: "3.3"
services:
  postgres:
    image: postgres:latest
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
    volumes:
      - "./db/data:/var/lib/postgresql/data"
      - "./db/init:/docker-entrypoint-initdb.d"
