version: "3.3"
services:
  db:
    image: postgres:latest
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: postgres -c shared_buffers=256MB
    environment:
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
    volumes:
      - "./db/data:/var/lib/postgresql/data"
  api:
    ports:
      - "3000:3000"
