name: CD
on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/**"
      - "api/**"
      - "frontend/**"

jobs:
  deploy:
    name: Deploy api
    defaults:
      run:
        working-directory: ./api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -a sps-api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_GH }}