name: Deploy functions

on:
  workflow_call:
    inputs:
      env-name:
        required: true
        type: string
    secrets:
      fb-token:
        required: true
jobs:
  deploy_function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get Yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/functions/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Instal dependencies
        run: cd functions && yarn install --frozen-lockfile
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions hosting:${{ inputs.env-name }}
        env:
          FIREBASE_TOKEN: ${{ secrets.fb-token }}
