name: Deploy functions

on:
  workflow_call:
    secrets:
      fb-token:
        required: true
        type: string

jobs:
  deploy_function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get Yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/functions/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Instal dependencies
        run: cd functions && yarn install --frozen-lockfile
      - name: Install firebase CLI
        run: curl -sL https://firebase.tools | bash
      — name: Create SA key
        run: echo '${{ secrets.fb-token }}' > $HOME/gcloud.json
      — name: Deploy Cloud Function
        run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && firebase-tools deploy --only functions --json
